# Generated by Django 5.0.6 on 2024-07-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='faculty',
        ),
        migrations.AddField(
            model_name='courseunit',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miutimetable.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miutimetable.semester'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.semester')),
            ],
        ),
    ]
