# Generated by Django 5.0.6 on 2024-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0002_semester_remove_courseunit_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('ONE', 'one'), ('TWO', 'two'), ('THREE', 'three')], default='ONE', max_length=20)),
            ],
        ),
    ]
