# Generated by Django 5.0.6 on 2024-07-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0003_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.academicyear')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_unit',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='is_cross_faculty',
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='semester',
        ),
        migrations.AddField(
            model_name='courseunit',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.courseunit'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.semester'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
