# Generated by Django 5.0.6 on 2024-07-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0004_academicyear_timetable_remove_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miutimetable.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miutimetable.semester'),
            preserve_default=False,
        ),
    ]
