# Generated by Django 5.0.6 on 2024-07-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0006_alter_course_name_alter_courseunit_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseunit',
            name='course',
        ),
        migrations.AddField(
            model_name='courseunit',
            name='courses',
            field=models.ManyToManyField(to='miutimetable.course'),
        ),
    ]
