# Generated by Django 5.0.6 on 2024-07-30 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miutimetable', '0007_remove_courseunit_course_courseunit_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miutimetable.lecturer')),
            ],
        ),
    ]
